# Generated by Django 4.0.2 on 2022-06-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0004_favoritething_profile_favorite_things"),
    ]

    operations = [
        migrations.AddField(
            model_name="favoritething",
            name="path_attribute",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
