# Generated by Django 4.0.2 on 2022-06-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0005_favoritething_path_attribute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoritething",
            name="path_attribute",
            field=models.CharField(blank=True, max_length=5096, null=True),
        ),
        migrations.AlterField(
            model_name="favoritething",
            name="svg_icon",
            field=models.FileField(upload_to="favorite_things/"),
        ),
    ]
