# Generated by Django 4.0.2 on 2022-06-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0007_favoritething_viewbox_attribute"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favoritething",
            name="path_attribute",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
