# Generated by Django 4.0.2 on 2022-06-03 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0009_map"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpage",
            name="map_overlay",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="profile.map",
            ),
        ),
        migrations.AddField(
            model_name="map",
            name="overlay_name",
            field=models.CharField(default="ilm_overlay.svg", max_length=150),
            preserve_default=False,
        ),
    ]
