# Generated by Django 4.0.7 on 2023-01-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_experience_link_experience_link_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritething',
            name='thing_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
