# Generated by Django 4.0.7 on 2023-03-20 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0012_alter_favoritething_thing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='example',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
