# Generated by Django 4.0.7 on 2023-05-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0013_design_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='link_title',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
