# Generated by Django 4.0.7 on 2023-07-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0014_alter_experience_link_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
