# Generated by Django 4.0.7 on 2023-07-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0015_alter_landingpage_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpage',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
