# Generated by Django 4.0.2 on 2022-05-26 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0002_domain"),
    ]

    operations = [
        migrations.CreateModel(
            name="Design",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_name", models.CharField(max_length=150)),
                ("name", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="LandingPage",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                ("headline", models.CharField(max_length=100)),
                ("avatar", models.ImageField(upload_to="")),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("resume", models.FileField(blank=True, null=True, upload_to="")),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="landing_page.design",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                ("exp_id", models.AutoField(primary_key=True, serialize=False)),
                ("company", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=65)),
                ("description", models.TextField(blank=True, null=True)),
                ("present", models.BooleanField()),
                ("start_year", models.IntegerField()),
                ("end_year", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
