# Generated by Django 4.0.2 on 2022-05-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_page", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpage",
            name="github",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="instagram",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="spotify",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="landingpage",
            name="twitter",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
