# Generated by Django 4.0.2 on 2022-05-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_page", "0002_landingpage_github_landingpage_instagram_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpage",
            name="linkedin",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
