# Generated by Django 4.0.2 on 2022-05-31 19:10

import landing_page.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_page", "0003_landingpage_linkedin"),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteThing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("thing_name", models.CharField(max_length=150)),
                (
                    "svg_icon",
                    models.FileField(
                        upload_to="favorite_things/",
                        validators=[landing_page.models.validate_svg],
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="landingpage",
            name="favorite_things",
            field=models.ManyToManyField(blank=True, to="landing_page.FavoriteThing"),
        ),
    ]
