# Generated by Django 4.0.2 on 2022-06-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_page", "0006_alter_favoritething_path_attribute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="favoritething",
            name="viewbox_attribute",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
