# Generated by Django 4.0.2 on 2022-11-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_page", "0010_landingpage_map_overlay_map_overlay_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="experience",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="link_title",
            field=models.URLField(blank=True, null=True),
        ),
    ]
