# Generated by Django 4.0.2 on 2022-07-10 15:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="domain",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="domain",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "invitation_code",
                    models.UUIDField(default=uuid.uuid4, editable=False),
                ),
                (
                    "linked_domain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.domain",
                    ),
                ),
            ],
        ),
    ]
