# Generated by Django 4.0.7 on 2023-05-22 17:03

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='file',
            field=models.FileField(blank=True, upload_to=content.models.document_upload_location),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(blank=True, upload_to=content.models.image_upload_location),
        ),
    ]
