default_install_hook_types: [pre-commit, prepare-commit-msg]
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/SethAngell/semantic-commit-formatter
    rev: v1.1.4
    hooks:
      - id: semantic_commit
        stages: [prepare-commit-msg]
