# Generated by Django 4.0.2 on 2022-06-24 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(max_length=128)),
                ("alt_text", models.TextField()),
                ("image", models.ImageField(upload_to="blog_images")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        editable=False,
                        null=True,
                        upload_to="blog_images/thumbnails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopicTags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=256)),
                ("markdown_body", models.TextField()),
                ("html_body", models.TextField(blank=True)),
                ("preview", models.CharField(blank=True, max_length=400)),
                ("slug", models.SlugField(blank=True, max_length=256, unique=True)),
                ("created_date", models.DateField(auto_now_add=True)),
                ("updated", models.DateField(auto_now=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PU", "Public"), ("PR", "Private")], max_length=2
                    ),
                ),
                ("image_encoding", models.CharField(blank=True, max_length=25)),
                (
                    "open_graph_protocol_description",
                    models.CharField(blank=True, max_length=500),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "header_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="blog.postimage",
                    ),
                ),
                ("tags", models.ManyToManyField(to="blog.TopicTags")),
            ],
        ),
    ]
