# Generated by Django 4.0.2 on 2022-06-25 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_blogpost_author_blog"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="parent_blog",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="blog.blog"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="blog_description",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
