# Generated by Django 4.0.2 on 2022-07-10 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogpost_parent_blog_alter_blog_blog_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="parent_blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.blog"
            ),
        ),
    ]
