# Generated by Django 4.0.2 on 2022-11-20 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blogpost_parent_blog_alter_blog_blog_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialImage",
            fields=[
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="blog.blogpost",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="blog_images/social_images"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="header_image",
        ),
        migrations.RemoveField(
            model_name="blogpost",
            name="image_encoding",
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="parent_blog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.blog"
            ),
        ),
    ]
