# Generated by Django 4.0.7 on 2023-02-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_socialimage_remove_blogpost_header_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='blog.topictags'),
        ),
    ]
