name: Build and Publish

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build-and-push-docker-image:
    if: github.event.pull_request.merged == true
    name: Builder Docker image and push to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build image and push to Github Container Registry
        uses: docker/build-push-action@v3
        with:
          context: ./app
          file: ./app/Dockerfile.prod
          push: true
          tags: |
            ghcr.io/sethangell/oys:latest
            ghcr.io/sethangell/oys:${{ secrets.MAJOR_VERSION }}.${{ secrets.MINOR_VERSION }}
      
      - name: Increment minor version value
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'MINOR_VERSION'
          value: $((${{ secrets.MINOR_VERSION }}+1))
          token: ${{ secrets.REPO_ACCESS_TOKEN }}



