name: Build and Publish

on:
  push:
    branches: [feature/ci-integration]
  pull_request:

jobs:
  build-and-push-docker-image:
    name: Builder Docker image and push to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build image and push to Github Container Registry
        uses: docker/build-push-action@v3
        with:
          context: ./app
          file: {context}/Dockerfile.prod
          push: true
          tags: ghcr.io/sethangell/oys:latest
          build-args: |
            "S3_KEY=${{ secrets.S3_KEY }}"
            "S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}"
            "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}"



