name: Notify

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Deploy To Production"]
    types:
      - completed

jobs:
  see-if-site-is-back-online:
    name: healthcheck
    runs-on: ubuntu-latest
    steps:
      - name: Give site some time to collectstatic and deploy
        run: sleep 60s
        shell: bash
      - name: Attempt to connect to personal landing page
        run: curl --connect-timeout 30 --retry 10 --retry-delay 5 https://sethangell.com
        shell: bash

  send-notification:
    runs-on: ubuntu-latest
    needs: see-if-site-is-back-online
    if: always()
    steps:
      - name: Post Pipeline Status
        uses: twilio-labs/actions-sms@v1
        with:
          fromPhoneNumber: ${{ secrets.FROM_NUMBER }}
          toPhoneNumber: ${{ secrets.TO_NUMBER }}
          message: "The Virtual Compound CI pipeline is complete. Status of Deployment is ${{ github.event.workflow_run.conclusion }}. Status of post deployment healthcheck is  ${{ steps.healthcheck.conclusion }}. See https://sethangell.com"
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_API_KEY: ${{ secrets.TWILIO_API_KEY }}
          TWILIO_API_SECRET: ${{ secrets.TWILIO_API_SECRET }}
    
